spring:
  application:
    name: carsales

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/carsales
    username: root
    password: Saurav@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3








